/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user profile
 */
export interface User {
  /**
   * The unique identifier for a user
   */
  id: number;
  /**
   * The user's mostly name
   */
  name: string;
  /**
   * The user's email address
   */
  email: string;
  /**
   * Indicates if the user's email is verified
   */
  isVerified?: boolean;
  /**
   * The user's mailing address
   */
  address?: {
    street: string;
    city: string;
    zipCode?: string;
    [k: string]: unknown;
  };
  /**
   * A list of tags associated with the user
   */
  tags?: string[];
  [k: string]: unknown;
}
